files:
  ignore:
    - 'src/vendor/**/*.*'
    - 'bower_components/**/*.*'
    - 'dist/**/*.*'
    - 'online/**/*.*'
rules:
  no-misspelled-properties: 0
  space-around-operator: 0
  property-sort-order:
    - 1
    -
      order: 'smacss'
